apiVersion: discovery.k8s.io/v1beta1
kind: EndpointSlice
metadata:
  name: demo-slice-1
  labels:
    kubernetes.io/service-name: demo
  addressType: IPv4
  ports:
  - name: http
    protocol: TCP
    port: 80
  endpoints:
    - addresses:
      - "10.0.0.1"
      conditions:
      ready: true